[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_type = "semver"
version_provider = "scm"
update_changelog_on_bump = true
bump_message = "chore(release): $current_version \u2192 $new_version"
allowed_prefixes = [ "Revert", "fixup!", "squash!"]
