# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
      exclude: (^firmware/external/.*)|(.*\.svd$)|(^docs/.*)|(^pcb/.*)|(CHANGELOG.md)
    - id: end-of-file-fixer
      exclude: (^firmware/external/.*)|(.*\.svd$)|(^docs/.*)|(^pcb/.*)|(CHANGELOG.md)
    - id: check-yaml
      args: [--allow-multiple-documents]
      exclude: .*\.svd$
    - id: check-added-large-files
      exclude: (^firmware/external/.*)|(.*\.svd$)|(^gd32_test_fw/.*)
      args: ['--maxkb=20000']
    - id: pretty-format-json
      args: [--autofix, --no-sort-keys]
      exclude: Pipfile.lock
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-xml
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: fix-byte-order-marker
      exclude: (^firmware/external/.*)|(^docs/.*)|(^pcb/.*)|(^gd32_test_fw/.*)
    - id: mixed-line-ending
      args: [--fix=lf]
      exclude: .*\.svd$
    - id: requirements-txt-fixer
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
      exclude: ^firmware/external/.*
  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
    - id: clang-format
      exclude: (^firmware/external/.*)|(.*\.proto$)|(.*\.svd$)|(^docs/.*)|(^pcb/.*)|(^zb_test/.*)|(^gd32_test_fw/.*)
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
